# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sippa/koodaus/triplane/oma/triplane

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sippa/koodaus/triplane/oma/triplane

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sippa/koodaus/triplane/oma/triplane/CMakeFiles /home/sippa/koodaus/triplane/oma/triplane//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sippa/koodaus/triplane/oma/triplane/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named triplane

# Build rule for target.
triplane: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triplane
.PHONY : triplane

# fast build rule for target.
triplane/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/build
.PHONY : triplane/fast

src/gfx/bitmap.o: src/gfx/bitmap.cpp.o
.PHONY : src/gfx/bitmap.o

# target to build an object file
src/gfx/bitmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/bitmap.cpp.o
.PHONY : src/gfx/bitmap.cpp.o

src/gfx/bitmap.i: src/gfx/bitmap.cpp.i
.PHONY : src/gfx/bitmap.i

# target to preprocess a source file
src/gfx/bitmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/bitmap.cpp.i
.PHONY : src/gfx/bitmap.cpp.i

src/gfx/bitmap.s: src/gfx/bitmap.cpp.s
.PHONY : src/gfx/bitmap.s

# target to generate assembly for a file
src/gfx/bitmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/bitmap.cpp.s
.PHONY : src/gfx/bitmap.cpp.s

src/gfx/extra.o: src/gfx/extra.cpp.o
.PHONY : src/gfx/extra.o

# target to build an object file
src/gfx/extra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/extra.cpp.o
.PHONY : src/gfx/extra.cpp.o

src/gfx/extra.i: src/gfx/extra.cpp.i
.PHONY : src/gfx/extra.i

# target to preprocess a source file
src/gfx/extra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/extra.cpp.i
.PHONY : src/gfx/extra.cpp.i

src/gfx/extra.s: src/gfx/extra.cpp.s
.PHONY : src/gfx/extra.s

# target to generate assembly for a file
src/gfx/extra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/extra.cpp.s
.PHONY : src/gfx/extra.cpp.s

src/gfx/fades.o: src/gfx/fades.cpp.o
.PHONY : src/gfx/fades.o

# target to build an object file
src/gfx/fades.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/fades.cpp.o
.PHONY : src/gfx/fades.cpp.o

src/gfx/fades.i: src/gfx/fades.cpp.i
.PHONY : src/gfx/fades.i

# target to preprocess a source file
src/gfx/fades.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/fades.cpp.i
.PHONY : src/gfx/fades.cpp.i

src/gfx/fades.s: src/gfx/fades.cpp.s
.PHONY : src/gfx/fades.s

# target to generate assembly for a file
src/gfx/fades.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/fades.cpp.s
.PHONY : src/gfx/fades.cpp.s

src/gfx/font.o: src/gfx/font.cpp.o
.PHONY : src/gfx/font.o

# target to build an object file
src/gfx/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/font.cpp.o
.PHONY : src/gfx/font.cpp.o

src/gfx/font.i: src/gfx/font.cpp.i
.PHONY : src/gfx/font.i

# target to preprocess a source file
src/gfx/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/font.cpp.i
.PHONY : src/gfx/font.cpp.i

src/gfx/font.s: src/gfx/font.cpp.s
.PHONY : src/gfx/font.s

# target to generate assembly for a file
src/gfx/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/font.cpp.s
.PHONY : src/gfx/font.cpp.s

src/gfx/gfx.o: src/gfx/gfx.cpp.o
.PHONY : src/gfx/gfx.o

# target to build an object file
src/gfx/gfx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/gfx.cpp.o
.PHONY : src/gfx/gfx.cpp.o

src/gfx/gfx.i: src/gfx/gfx.cpp.i
.PHONY : src/gfx/gfx.i

# target to preprocess a source file
src/gfx/gfx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/gfx.cpp.i
.PHONY : src/gfx/gfx.cpp.i

src/gfx/gfx.s: src/gfx/gfx.cpp.s
.PHONY : src/gfx/gfx.s

# target to generate assembly for a file
src/gfx/gfx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/gfx/gfx.cpp.s
.PHONY : src/gfx/gfx.cpp.s

src/io/dksfile.o: src/io/dksfile.cpp.o
.PHONY : src/io/dksfile.o

# target to build an object file
src/io/dksfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/dksfile.cpp.o
.PHONY : src/io/dksfile.cpp.o

src/io/dksfile.i: src/io/dksfile.cpp.i
.PHONY : src/io/dksfile.i

# target to preprocess a source file
src/io/dksfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/dksfile.cpp.i
.PHONY : src/io/dksfile.cpp.i

src/io/dksfile.s: src/io/dksfile.cpp.s
.PHONY : src/io/dksfile.s

# target to generate assembly for a file
src/io/dksfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/dksfile.cpp.s
.PHONY : src/io/dksfile.cpp.s

src/io/joystick.o: src/io/joystick.cpp.o
.PHONY : src/io/joystick.o

# target to build an object file
src/io/joystick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/joystick.cpp.o
.PHONY : src/io/joystick.cpp.o

src/io/joystick.i: src/io/joystick.cpp.i
.PHONY : src/io/joystick.i

# target to preprocess a source file
src/io/joystick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/joystick.cpp.i
.PHONY : src/io/joystick.cpp.i

src/io/joystick.s: src/io/joystick.cpp.s
.PHONY : src/io/joystick.s

# target to generate assembly for a file
src/io/joystick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/joystick.cpp.s
.PHONY : src/io/joystick.cpp.s

src/io/mouse.o: src/io/mouse.cpp.o
.PHONY : src/io/mouse.o

# target to build an object file
src/io/mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/mouse.cpp.o
.PHONY : src/io/mouse.cpp.o

src/io/mouse.i: src/io/mouse.cpp.i
.PHONY : src/io/mouse.i

# target to preprocess a source file
src/io/mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/mouse.cpp.i
.PHONY : src/io/mouse.cpp.i

src/io/mouse.s: src/io/mouse.cpp.s
.PHONY : src/io/mouse.s

# target to generate assembly for a file
src/io/mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/mouse.cpp.s
.PHONY : src/io/mouse.cpp.s

src/io/sdl_compat.o: src/io/sdl_compat.cpp.o
.PHONY : src/io/sdl_compat.o

# target to build an object file
src/io/sdl_compat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/sdl_compat.cpp.o
.PHONY : src/io/sdl_compat.cpp.o

src/io/sdl_compat.i: src/io/sdl_compat.cpp.i
.PHONY : src/io/sdl_compat.i

# target to preprocess a source file
src/io/sdl_compat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/sdl_compat.cpp.i
.PHONY : src/io/sdl_compat.cpp.i

src/io/sdl_compat.s: src/io/sdl_compat.cpp.s
.PHONY : src/io/sdl_compat.s

# target to generate assembly for a file
src/io/sdl_compat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/sdl_compat.cpp.s
.PHONY : src/io/sdl_compat.cpp.s

src/io/sound.o: src/io/sound.cpp.o
.PHONY : src/io/sound.o

# target to build an object file
src/io/sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/sound.cpp.o
.PHONY : src/io/sound.cpp.o

src/io/sound.i: src/io/sound.cpp.i
.PHONY : src/io/sound.i

# target to preprocess a source file
src/io/sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/sound.cpp.i
.PHONY : src/io/sound.cpp.i

src/io/sound.s: src/io/sound.cpp.s
.PHONY : src/io/sound.s

# target to generate assembly for a file
src/io/sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/sound.cpp.s
.PHONY : src/io/sound.cpp.s

src/io/timing.o: src/io/timing.cpp.o
.PHONY : src/io/timing.o

# target to build an object file
src/io/timing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/timing.cpp.o
.PHONY : src/io/timing.cpp.o

src/io/timing.i: src/io/timing.cpp.i
.PHONY : src/io/timing.i

# target to preprocess a source file
src/io/timing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/timing.cpp.i
.PHONY : src/io/timing.cpp.i

src/io/timing.s: src/io/timing.cpp.s
.PHONY : src/io/timing.s

# target to generate assembly for a file
src/io/timing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/timing.cpp.s
.PHONY : src/io/timing.cpp.s

src/io/video.o: src/io/video.cpp.o
.PHONY : src/io/video.o

# target to build an object file
src/io/video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/video.cpp.o
.PHONY : src/io/video.cpp.o

src/io/video.i: src/io/video.cpp.i
.PHONY : src/io/video.i

# target to preprocess a source file
src/io/video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/video.cpp.i
.PHONY : src/io/video.cpp.i

src/io/video.s: src/io/video.cpp.s
.PHONY : src/io/video.s

# target to generate assembly for a file
src/io/video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/io/video.cpp.s
.PHONY : src/io/video.cpp.s

src/menus/tripmenu.o: src/menus/tripmenu.cpp.o
.PHONY : src/menus/tripmenu.o

# target to build an object file
src/menus/tripmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/menus/tripmenu.cpp.o
.PHONY : src/menus/tripmenu.cpp.o

src/menus/tripmenu.i: src/menus/tripmenu.cpp.i
.PHONY : src/menus/tripmenu.i

# target to preprocess a source file
src/menus/tripmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/menus/tripmenu.cpp.i
.PHONY : src/menus/tripmenu.cpp.i

src/menus/tripmenu.s: src/menus/tripmenu.cpp.s
.PHONY : src/menus/tripmenu.s

# target to generate assembly for a file
src/menus/tripmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/menus/tripmenu.cpp.s
.PHONY : src/menus/tripmenu.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/tools/lvledit/lvledit.o: src/tools/lvledit/lvledit.cpp.o
.PHONY : src/tools/lvledit/lvledit.o

# target to build an object file
src/tools/lvledit/lvledit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/tools/lvledit/lvledit.cpp.o
.PHONY : src/tools/lvledit/lvledit.cpp.o

src/tools/lvledit/lvledit.i: src/tools/lvledit/lvledit.cpp.i
.PHONY : src/tools/lvledit/lvledit.i

# target to preprocess a source file
src/tools/lvledit/lvledit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/tools/lvledit/lvledit.cpp.i
.PHONY : src/tools/lvledit/lvledit.cpp.i

src/tools/lvledit/lvledit.s: src/tools/lvledit/lvledit.cpp.s
.PHONY : src/tools/lvledit/lvledit.s

# target to generate assembly for a file
src/tools/lvledit/lvledit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/tools/lvledit/lvledit.cpp.s
.PHONY : src/tools/lvledit/lvledit.cpp.s

src/triplane.o: src/triplane.cpp.o
.PHONY : src/triplane.o

# target to build an object file
src/triplane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/triplane.cpp.o
.PHONY : src/triplane.cpp.o

src/triplane.i: src/triplane.cpp.i
.PHONY : src/triplane.i

# target to preprocess a source file
src/triplane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/triplane.cpp.i
.PHONY : src/triplane.cpp.i

src/triplane.s: src/triplane.cpp.s
.PHONY : src/triplane.s

# target to generate assembly for a file
src/triplane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/triplane.cpp.s
.PHONY : src/triplane.cpp.s

src/util/random.o: src/util/random.cpp.o
.PHONY : src/util/random.o

# target to build an object file
src/util/random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/util/random.cpp.o
.PHONY : src/util/random.cpp.o

src/util/random.i: src/util/random.cpp.i
.PHONY : src/util/random.i

# target to preprocess a source file
src/util/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/util/random.cpp.i
.PHONY : src/util/random.cpp.i

src/util/random.s: src/util/random.cpp.s
.PHONY : src/util/random.s

# target to generate assembly for a file
src/util/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/util/random.cpp.s
.PHONY : src/util/random.cpp.s

src/util/wutil.o: src/util/wutil.cpp.o
.PHONY : src/util/wutil.o

# target to build an object file
src/util/wutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/util/wutil.cpp.o
.PHONY : src/util/wutil.cpp.o

src/util/wutil.i: src/util/wutil.cpp.i
.PHONY : src/util/wutil.i

# target to preprocess a source file
src/util/wutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/util/wutil.cpp.i
.PHONY : src/util/wutil.cpp.i

src/util/wutil.s: src/util/wutil.cpp.s
.PHONY : src/util/wutil.s

# target to generate assembly for a file
src/util/wutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/util/wutil.cpp.s
.PHONY : src/util/wutil.cpp.s

src/world/fobjects.o: src/world/fobjects.cpp.o
.PHONY : src/world/fobjects.o

# target to build an object file
src/world/fobjects.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/fobjects.cpp.o
.PHONY : src/world/fobjects.cpp.o

src/world/fobjects.i: src/world/fobjects.cpp.i
.PHONY : src/world/fobjects.i

# target to preprocess a source file
src/world/fobjects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/fobjects.cpp.i
.PHONY : src/world/fobjects.cpp.i

src/world/fobjects.s: src/world/fobjects.cpp.s
.PHONY : src/world/fobjects.s

# target to generate assembly for a file
src/world/fobjects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/fobjects.cpp.s
.PHONY : src/world/fobjects.cpp.s

src/world/plane.o: src/world/plane.cpp.o
.PHONY : src/world/plane.o

# target to build an object file
src/world/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/plane.cpp.o
.PHONY : src/world/plane.cpp.o

src/world/plane.i: src/world/plane.cpp.i
.PHONY : src/world/plane.i

# target to preprocess a source file
src/world/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/plane.cpp.i
.PHONY : src/world/plane.cpp.i

src/world/plane.s: src/world/plane.cpp.s
.PHONY : src/world/plane.s

# target to generate assembly for a file
src/world/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/plane.cpp.s
.PHONY : src/world/plane.cpp.s

src/world/terrain.o: src/world/terrain.cpp.o
.PHONY : src/world/terrain.o

# target to build an object file
src/world/terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/terrain.cpp.o
.PHONY : src/world/terrain.cpp.o

src/world/terrain.i: src/world/terrain.cpp.i
.PHONY : src/world/terrain.i

# target to preprocess a source file
src/world/terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/terrain.cpp.i
.PHONY : src/world/terrain.cpp.i

src/world/terrain.s: src/world/terrain.cpp.s
.PHONY : src/world/terrain.s

# target to generate assembly for a file
src/world/terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/terrain.cpp.s
.PHONY : src/world/terrain.cpp.s

src/world/tmexept.o: src/world/tmexept.cpp.o
.PHONY : src/world/tmexept.o

# target to build an object file
src/world/tmexept.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tmexept.cpp.o
.PHONY : src/world/tmexept.cpp.o

src/world/tmexept.i: src/world/tmexept.cpp.i
.PHONY : src/world/tmexept.i

# target to preprocess a source file
src/world/tmexept.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tmexept.cpp.i
.PHONY : src/world/tmexept.cpp.i

src/world/tmexept.s: src/world/tmexept.cpp.s
.PHONY : src/world/tmexept.s

# target to generate assembly for a file
src/world/tmexept.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tmexept.cpp.s
.PHONY : src/world/tmexept.cpp.s

src/world/tripai.o: src/world/tripai.cpp.o
.PHONY : src/world/tripai.o

# target to build an object file
src/world/tripai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripai.cpp.o
.PHONY : src/world/tripai.cpp.o

src/world/tripai.i: src/world/tripai.cpp.i
.PHONY : src/world/tripai.i

# target to preprocess a source file
src/world/tripai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripai.cpp.i
.PHONY : src/world/tripai.cpp.i

src/world/tripai.s: src/world/tripai.cpp.s
.PHONY : src/world/tripai.s

# target to generate assembly for a file
src/world/tripai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripai.cpp.s
.PHONY : src/world/tripai.cpp.s

src/world/tripaudio.o: src/world/tripaudio.cpp.o
.PHONY : src/world/tripaudio.o

# target to build an object file
src/world/tripaudio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripaudio.cpp.o
.PHONY : src/world/tripaudio.cpp.o

src/world/tripaudio.i: src/world/tripaudio.cpp.i
.PHONY : src/world/tripaudio.i

# target to preprocess a source file
src/world/tripaudio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripaudio.cpp.i
.PHONY : src/world/tripaudio.cpp.i

src/world/tripaudio.s: src/world/tripaudio.cpp.s
.PHONY : src/world/tripaudio.s

# target to generate assembly for a file
src/world/tripaudio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripaudio.cpp.s
.PHONY : src/world/tripaudio.cpp.s

src/world/tripmis.o: src/world/tripmis.cpp.o
.PHONY : src/world/tripmis.o

# target to build an object file
src/world/tripmis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripmis.cpp.o
.PHONY : src/world/tripmis.cpp.o

src/world/tripmis.i: src/world/tripmis.cpp.i
.PHONY : src/world/tripmis.i

# target to preprocess a source file
src/world/tripmis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripmis.cpp.i
.PHONY : src/world/tripmis.cpp.i

src/world/tripmis.s: src/world/tripmis.cpp.s
.PHONY : src/world/tripmis.s

# target to generate assembly for a file
src/world/tripmis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triplane.dir/build.make CMakeFiles/triplane.dir/src/world/tripmis.cpp.s
.PHONY : src/world/tripmis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... triplane"
	@echo "... src/gfx/bitmap.o"
	@echo "... src/gfx/bitmap.i"
	@echo "... src/gfx/bitmap.s"
	@echo "... src/gfx/extra.o"
	@echo "... src/gfx/extra.i"
	@echo "... src/gfx/extra.s"
	@echo "... src/gfx/fades.o"
	@echo "... src/gfx/fades.i"
	@echo "... src/gfx/fades.s"
	@echo "... src/gfx/font.o"
	@echo "... src/gfx/font.i"
	@echo "... src/gfx/font.s"
	@echo "... src/gfx/gfx.o"
	@echo "... src/gfx/gfx.i"
	@echo "... src/gfx/gfx.s"
	@echo "... src/io/dksfile.o"
	@echo "... src/io/dksfile.i"
	@echo "... src/io/dksfile.s"
	@echo "... src/io/joystick.o"
	@echo "... src/io/joystick.i"
	@echo "... src/io/joystick.s"
	@echo "... src/io/mouse.o"
	@echo "... src/io/mouse.i"
	@echo "... src/io/mouse.s"
	@echo "... src/io/sdl_compat.o"
	@echo "... src/io/sdl_compat.i"
	@echo "... src/io/sdl_compat.s"
	@echo "... src/io/sound.o"
	@echo "... src/io/sound.i"
	@echo "... src/io/sound.s"
	@echo "... src/io/timing.o"
	@echo "... src/io/timing.i"
	@echo "... src/io/timing.s"
	@echo "... src/io/video.o"
	@echo "... src/io/video.i"
	@echo "... src/io/video.s"
	@echo "... src/menus/tripmenu.o"
	@echo "... src/menus/tripmenu.i"
	@echo "... src/menus/tripmenu.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/tools/lvledit/lvledit.o"
	@echo "... src/tools/lvledit/lvledit.i"
	@echo "... src/tools/lvledit/lvledit.s"
	@echo "... src/triplane.o"
	@echo "... src/triplane.i"
	@echo "... src/triplane.s"
	@echo "... src/util/random.o"
	@echo "... src/util/random.i"
	@echo "... src/util/random.s"
	@echo "... src/util/wutil.o"
	@echo "... src/util/wutil.i"
	@echo "... src/util/wutil.s"
	@echo "... src/world/fobjects.o"
	@echo "... src/world/fobjects.i"
	@echo "... src/world/fobjects.s"
	@echo "... src/world/plane.o"
	@echo "... src/world/plane.i"
	@echo "... src/world/plane.s"
	@echo "... src/world/terrain.o"
	@echo "... src/world/terrain.i"
	@echo "... src/world/terrain.s"
	@echo "... src/world/tmexept.o"
	@echo "... src/world/tmexept.i"
	@echo "... src/world/tmexept.s"
	@echo "... src/world/tripai.o"
	@echo "... src/world/tripai.i"
	@echo "... src/world/tripai.s"
	@echo "... src/world/tripaudio.o"
	@echo "... src/world/tripaudio.i"
	@echo "... src/world/tripaudio.s"
	@echo "... src/world/tripmis.o"
	@echo "... src/world/tripmis.i"
	@echo "... src/world/tripmis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

